version: "1.0"

services:

  app:
    image: ${DOCKER_USER_NAME}/${IMAGE_NAME}:${IMAGE_TAG}
    container_name: assignment-group-portal
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "5000"
    depends_on:
      - redis
    networks:
      - assignment-network

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    expose:
      - "6379"
    networks:
      - assignment-network

  nginx:
    image: nginx:1.27-alpine
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - assignment-network

volumes:
  redis-data:

networks:
  assignment-network:
    driver: bridge
