name: deployment-via-ssh

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build \
            -t ${{ secrets.DOCKER_USER_NAME }}/${{ secrets.IMAGE_NAME }}:${{ secrets.IMAGE_TAG }} .

      - name: Push Docker Image
        run: |
          docker push \
            ${{ secrets.DOCKER_USER_NAME }}/${{ secrets.IMAGE_NAME }}:${{ secrets.IMAGE_TAG }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.TARGET_HOST }}
          username: ${{ secrets.TARGET_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |

            PROJECT_DIR="/home/${{ secrets.TARGET_USER }}/assignment-group-portal"
            REPO_URL="https://github.com/Yashwanthgowdam123/3tier_docker_deployment_assignment.git"

            # Install Docker if missing
            if ! command -v docker >/dev/null 2>&1; then
              curl -fsSL https://get.docker.com | sudo sh
              sudo usermod -aG docker $USER
            fi

            # Install Docker Compose if missing
            if ! docker compose version >/dev/null 2>&1; then
              sudo apt-get update
              sudo apt-get install -y docker-compose-plugin
            fi

            # Install Git if missing
            if ! command -v git >/dev/null 2>&1; then
              sudo apt-get update
              sudo apt-get install -y git
            fi

            # Clone or Update Repository
            if [ ! -d "$PROJECT_DIR/.git" ]; then
              git clone "$REPO_URL" "$PROJECT_DIR"
            else
              cd "$PROJECT_DIR"
              git pull origin main
            fi
            sudo su
            cd "$PROJECT_DIR"

            # Create .env
            cat > .env <<'EOF'
            ${{ secrets.ENV_FILE }}
            EOF

            # Export image variables for docker compose
            export DOCKER_USER_NAME="${{ secrets.DOCKER_USER_NAME }}"
            export IMAGE_NAME="${{ secrets.IMAGE_NAME }}"
            export IMAGE_TAG="${{ secrets.IMAGE_TAG }}"
            sudo su 
            docker login -u "${{ secrets.DOCKER_USER_NAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"

            docker compose pull

            docker compose down || true

            docker compose up -d --force-recreate

            docker image prune -f
